agents/urls.py
from django.urls import path

from agents.views import index, listagent, saveagent, deleteagent, updateagent, rechercheragent, \
    liste_attribution_agent, list_comptable, index_base, connexionuser, active_compte, rechercher_comptable

app_name = 'mefpai'

urlpatterns = [
    path('', index_base, name='accueil'),
    path('accueil', index_base, name='accueil'),
    path('personnels', listagent, name='list-agent'),
    path('login', connexionuser, name='connexionuser'),
    path('comptables', list_comptable, name='list-comptable'),
    path('rechercher/comptable', rechercher_comptable, name='rechercher_comptable'),
    path('comptables/compte/<int:pk>/', active_compte, name='active_compte'),
    path('comptables/journal/<int:pk>', liste_attribution_agent, name='journal'),
    path('saveAgent', saveagent, name='saveagent'),
    path('personnels/<int:pk>/', updateagent, name='updateAgent'),
    path('personnels/<int:pk>/', deleteagent, name='deleteAgent'),
    path('rechercher', rechercheragent, name='rechercheragent'),
    path('personnels/journal/<int:pk>', liste_attribution_agent, name='journal'),
]

gestionTicket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from agents.views import listagent, saveagent, updateagent, rechercheragent, liste_attribution_agent, list_comptable, \
    connexionuser, index_base

from gestionTicket.views import index

urlpatterns = [
    path('', index, name='index'),
    path('administration/', admin.site.urls),
    path('mefpai/', include('agents.urls'))
]

agents/models.py
from django.db import models

# Create your models here.
from utilisateur.models import Utilisateur


class Agents(models.Model):
    sexe_option = [('m', 'Masculin'), ('f', 'Féminin')]
    direction_option = [('DAGE', 'DAGE'), ('DFPT', 'DFPT'), ('PEJA', 'PEJA'), ('CI', 'Cellule Informatique'), ('CG', 'Cellule Genre')]
    agent_id = models.BigAutoField(primary_key=True)
    first_name = models.CharField(verbose_name='Prénom', blank=False, max_length=100)
    last_name = models.CharField(verbose_name='Nom de famille', blank=False, max_length=100)
    email_institutionnel = models.EmailField(verbose_name='Email Institutionnel', blank=False, unique=True, max_length=100)
    sexe = models.CharField(choices=sexe_option, verbose_name='Sexe', blank=False, max_length=100)
    tel1 = models.CharField(verbose_name='Numéro Téléphone', blank=False, unique=True, max_length=9)
    direction = models.CharField(choices=direction_option, blank=False, verbose_name="Direction", max_length=100)
    post_occupe = models.CharField(verbose_name='Poste Occupé', blank=False, max_length=100)
    autre_tel = models.CharField(verbose_name='Autre Numéro', blank=True, max_length=9)
    utilisateur_ref = models.ForeignKey(Utilisateur, verbose_name='Responsable', blank=False, on_delete=models.CASCADE, related_name='Utilisateur')

agents/forms.py
from django import forms

from agents.models import Agents
from utilisateur.models import Utilisateur


class AgentsForms(forms.ModelForm):
    class Meta:
        sexe_option = [('m', 'Masculin'), ('f', 'Féminin')]
        model = Agents
        fields = ('first_name', 'last_name', 'email_institutionnel','sexe', 'direction', 'tel1', 'post_occupe', 'autre_tel', 'utilisateur_ref')

        widgets = {
            'last_name': forms.TextInput(attrs={'class': 'from-control'}),
            'email_institutionnel': forms.TextInput(attrs={'class': 'from-control'}),
            'sexe': forms.Select(attrs={'class': 'form-control col-sm-2'}),
            'tel1': forms.TextInput(attrs={'class': 'from-control'}),
            'direction': forms.Select(attrs={'class': 'form-control col-sm-2'}),
            'post_occupe': forms.TextInput(attrs={'class': 'from-control'}),
            'autre_tel': forms.TextInput(attrs={'class': 'from-control'}),
            'utilisateur_ref': forms.Select(attrs={'class': 'form-control col-sm-2'})
        }


class UtilisateurForms(forms.ModelForm):
    class Meta:
        sexe_option = [('m', 'Masculin'), ('f', 'Féminin')]
        model = Utilisateur
        fields = ('first_name', 'last_name', 'username', 'password', 'groups','email', 'sexe', 'direction', 'tel1', 'post_occupe', 'is_active')

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'from-control'}),
            'last_name': forms.TextInput(attrs={'class': 'from-control'}),
            'username': forms.TextInput(attrs={'class': 'from-control'}),
            'password': forms.TextInput(attrs={'class': 'from-control', 'type': 'password'}),
            'groups': forms.Select(attrs={'class': 'form-control col-sm-2'}),
            'email': forms.TextInput(attrs={'class': 'from-control'}),
            'sexe': forms.Select(attrs={'class': 'form-control col-sm-2'}),
            'tel1': forms.TextInput(attrs={'class': 'from-control'}),
            'direction': forms.Select(attrs={'class': 'form-control col-sm-2'}),
            'post_occupe': forms.TextInput(attrs={'class': 'from-control'}),
            'autre_tel': forms.TextInput(attrs={'class': 'from-control'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'from-control '}),
        }

agents/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login
# Create your views here.
from agents.forms import AgentsForms, UtilisateurForms
from agents.models import Agents
from django.http import JsonResponse

from attribution.models import Attribution
from utilisateur.models import Utilisateur
from django.contrib.auth import logout


def index(request):
    return render(request, 'accueil.html')


def index_base(request):
    return render(request, 'base.html')


def saveagent(request):
    if request.method == 'POST':
        form = AgentsForms(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('personnels')
    else:
        form = AgentsForms()
        agent = Agents.objects.all()
        return render(request, 'agent.html', {'agent': agent, 'form': form})


def listagent(request):
    form = AgentsForms()
    agent = Agents.objects.all()
    taille = len(agent)
    return render(request, 'agent.html', {'agent': agent, 'form': form, 'taille': taille})


def updateagent(request, pk):
    agent = Agents.objects.get(pk=pk)
    form = AgentsForms(instance=agent)

    if request.method == 'POST':
        form = AgentsForms(request.POST, instance=agent)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('personnels')
    return render(request, 'agent.html', {'agent': agent, 'form': form})


def active_compte(request, pk):
    if pk != '':
        utilisateur = Utilisateur.objects.get(utilisateur_id=pk)
        if utilisateur.is_active:
            utilisateur.is_active = False
            utilisateur.save()
            return HttpResponseRedirect('/mefpai/comptables')
        elif not utilisateur.is_active:
            utilisateur.is_active = True
            utilisateur.save()
            return HttpResponseRedirect('/mefpai/comptables')


def rechercheragent(request):
    form = AgentsForms()
    try:
        if request.method == 'POST':
            email = request.POST['emailagent']
            agent = Agents.objects.get(email_institutionnel=email)
            nbr = 1
            return render(request, 'rechercher.html', {'agent': agent, 'form': form, 'nbr': nbr, 'email': email})
    except:
        agent = ''
        return render(request, 'rechercher.html', {'agent': agent, 'form': form, 'email': email})
    return HttpResponseRedirect('personnels')


def rechercher_comptable(request):
    form = UtilisateurForms()
    try:
        if request.method == 'POST':
            email = request.POST['emailagent']
            agent = Utilisateur.objects.get(email_institutionnel=email)
            nbr = 1
            return render(request, 'recherchercomptable.html', {'agent': agent, 'form': form, 'nbr': nbr, 'email': email})
    except:
        agent = ''
        return render(request, 'recherchercomptable.html', {'agent': agent, 'form': form, 'email': email})
    return HttpResponseRedirect('/mefpai/comptables')


def liste_attribution_agent(request, pk):
    if pk:
        form = AgentsForms()
        agent = Agents.objects.get(pk=pk)
        attribution = Attribution.objects.filter(agent=agent)
        return render(request, 'journal.html', {'agent': agent, 'attribution': attribution, 'form': form})
    return HttpResponseRedirect('personnels')


def list_comptable(request):
    form = UtilisateurForms()
    comptables = Utilisateur.objects.all()
    return render(request, 'comptables.html', {'comptables': comptables, 'form': form})


def deleteagent(request, pk):
    agent = Agents.objects.get(pk=pk)
    agent.objects.delete()
    return render(request, 'delete.html', {'agent': agent})


def connexionuser(request):
    form = AgentsForms()
    try:
        if request.method == 'POST':
            email = request.POST['email']
            passwd = request.POST['passwd']
            user = Utilisateur.objects.get(email_institutionnel=email, password=passwd)
            agent = Agents.objects.all()
            return render(request, 'base.html', {'agent': agent, 'form': form, 'user': user})
        return HttpResponseRedirect('/')
    except:
        return HttpResponseRedirect('/')
    return HttpResponseRedirect('/')


def logout_view(request):
    logout(request)

agents/templates/layout/baseIndex.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="UTF-8">
	<title>Sama Ticket</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

	<!-- Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700' rel='stylesheet' type='text/css'>

	<!-- Css -->
	<link rel="stylesheet" href="{% static 'css/nivo-slider.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/responsive.css' %}">

	<!-- jS -->
	<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/jquery.nivo.slider.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/jquery.nicescroll.js' %}"></script>
	<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}" type="text/javascript"></script>

</head>
<body>

    {% block menu %}
        {% include "layout/menu.html" %}
    {% endblock menu%}


	{% block content %}

	{% endblock content%}


    {% block footer %}
        {% include "layout/footer.html" %}
    {% endblock footer %}


	<a id="back-top" href="#"></a>

	{% block extrascript %}

	{% endblock extrascript %}
</body>
</html>

agents/templates/layout/footer.html
{% load static %}
	<!-- FOOTER Start
    ================================================== -->

	<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<div class="block clearfix">
						<a href="#">
							<img src="{% static 'images/footer-logo.png' %}" alt="">
						</a>
						<p>
							Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s
						</p>
						<h4 class="connect-heading">VISITEZ NOS PAGES</h4>
						<ul class="social-icon">
							<li>
								<a class="facebook-icon" href="#">
									<i class="fa fa-facebook"></i>
								</a>
							</li>
							<li>
								<a class="plus-icon" href="#">
									<i class="fa fa-google-plus"></i>
								</a>
							</li>
							<li>
								<a class="twitter-icon" href="#">
									<i class="fa fa-twitter"></i>
								</a>
							</li>
							<li>
								<a class="pinterest-icon" href="#">
									<i class="fa fa-pinterest"></i>
								</a>
							</li>
							<li>
								<a class="linkedin-icon" href="#">
									<i class="fa fa-linkedin"></i>
								</a>
							</li>
						</ul>	<!-- End Of /.social-icon -->
					</div>	<!-- End Of /.block -->
				</div> <!-- End Of /.Col-md-4 -->
				<div class="col-md-4">
					<div class="block">
						<h4>CONTACTEZ-NOUS</h4>
						<p ><i class="fa  fa-map-marker"></i> <span>Sama Ticket </span>Ministère de l'Emploi de la Formation Professionnelle de l'Apprentissage et de l'Insertion</p>
						<p> <i class="fa  fa-phone"></i> <span>Téléphone :</span> (+221) 77 658 69 40 </p>

						<p> <i class="fa  fa-mobile"></i> <span>Fixe :</span> (+221) 33 820 33 33</p>

						<p class="mail"><i class="fa  fa-envelope"></i>Email : <span>celluleinformatique@.mefpa.gouv.sn</span></p>
					</div>	<!-- End Of /.block -->
				</div> <!-- End Of Col-md-3 -->
				<div class="col-md-4">
					<div class="block">
						<h4>Prochainnement Vos Plats</h4>
						<div class="media">
						  	<a class="pull-left" href="#">
						    	<img class="media-object" src="{% static 'images/product-item.jpg' %}" alt="...">
						  	</a>
						  	<a class="pull-left" href="#">
						    	<img class="media-object" src="{% static 'images/product-item.jpg' %}" alt="...">
						  	</a>
						  	<a class="pull-left" href="#">
						    	<img class="media-object" src="{% static 'images/product-item.jpg' %}" alt="...">
						  	</a>
						</div>	<!-- End Of /.media -->
					</div>	<!-- End Of /.block -->
				</div> <!-- End Of Col-md-3 -->
			</div> <!-- End Of /.row -->
		</div> <!-- End Of /.Container -->



	<!-- FOOTER-BOTTOM Start
    ================================================== -->

		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<ul class="cash-out pull-left">
							<li>
								<a href="#">
									<img src="{% static 'images/American-Express.png' %}" alt="">
								</a>
							</li>
							<li>
								<a href="#">
									<img src="{% static 'images/PayPal.png' %}" alt="">
								</a>
							</li>
							<li>
								<a href="#">
									<img src="{% static 'images/Maestro.png' %}" alt="">
								</a>
							</li>
							<li>
								<a href="#">
									<img src="{% static 'images/Visa.png' %}" alt="">
								</a>
							</li>
							<li>
								<a href="#">
									<img src="{% static 'images/Visa-Electron.png' %}" alt="">
								</a>
							</li>
						</ul>
						<p class="copyright-text pull-right">Cellule Informatique @2020 MEFPAI</p>
					</div>	<!-- End Of /.col-md-12 -->
				</div>	<!-- End Of /.row -->
			</div>	<!-- End Of /.container -->
		</div>	<!-- End Of /.footer-bottom -->
	</footer> <!-- End Of Footer -->

agents/templates/layout/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="UTF-8">
	<title>Sama Ticket</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

	<!-- Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700' rel='stylesheet' type='text/css'>

	<!-- Css -->
	<link rel="stylesheet" href="{% static 'css/nivo-slider.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/responsive.css' %}">

	<!-- jS -->
	<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/jquery.nivo.slider.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/jquery.nicescroll.js' %}"></script>
	<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}" type="text/javascript"></script>

</head>
<body>

    {% block nav %}
        {% include "layout/nav.html" %}
    {% endblock nav%}


	{% block content %}

	{% endblock content%}


    {% block footer %}
        {% include "layout/footer.html" %}
    {% endblock footer %}


	<a id="back-top" href="#"></a>

	{% block extrascript %}

	{% endblock extrascript %}
</body>
</html>

agents/templates/layout/menu.html
{% load static %}
{% load bootstrap_icons %}
<!-- TOP HEADER Start
    ================================================== -->

	<section id="top">
		<div class="container">
			<div class="row">
				<div class="col-md-7">
					<p class="contact-action"><i class="fa fa-phone-square"></i>Pour plus d'information contacter: <strong>+221 292 90 54</strong></p>
				</div>
				<div class="col-md-2">

				</div>

				<div class="col-md-3 clearfix">
					<ul class="login-cart">
						<li>
							<a data-toggle="modal" data-target="#myModal" href="#">
								<span style="font-size:large; position:relative; bottom:30%;">
									Déconnexion
								</span>
							</a>
						</li>
					</ul>
				</div>

			</div> <!-- End Of /.row -->
		</div>	<!-- End Of /.Container -->


	<!-- MODAL Start
    	================================================== -->

	</section>  <!-- End of /Section -->



	<!-- LOGO Start
    ================================================== -->

	<header>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<a href="">
						<img src="{% static 'images/logo.png' %}" alt="logo">
					</a>
				</div>	<!-- End of /.col-md-12 -->
			</div>	<!-- End of /.row -->
		</div>	<!-- End of /.container -->
	</header> <!-- End of /Header -->




	<!-- MENU Start
    ================================================== -->

	<nav class="navbar navbar-default">
		<div class="container">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		    </div> <!-- End of /.navbar-header -->

		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      	<ul class="nav navbar-nav nav-main">
		        	<li class="active"><a href="{% url 'mefpai:accueil' %}">ACCUEIL</a></li>
					<li><a href="{% url 'mefpai:list-comptable' %}">COMPTABLES</a></li>
					<li><a href="{% url 'mefpai:list-agent' %}">AGENT</a></li>
					<li><a href="">ATTRIBUTION</a></li>
					<li class="dropdown">
						<a href="#">
							DIRECTIONS
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
						   <li><a  href="#">DAGE</a></li>
						    <li><a  href="#">DFPT</a></li>
							<li><a  href="#">PEJA</a></li>
						</ul>
					</li> <!-- End of /.dropdown -->

					<li class="dropdown">
						<a href="#">
							CELLULES
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
						    <li><a  href="#">Informatique</a></li>
						    <li><a  href="#">Genre</a></li>
						</ul>
					</li> <!-- End of /.dropdown -->

					<li class="dropdown">
						<a href="#">
							{% bs_icon 'person-circle' color='black' size='1.5em' %}
						</a>
						<ul class="dropdown-menu">
						    <li><a  href="#">Profil</a></li>
							<li><a  href="#">Déconnexion</a></li>
						</ul>
					</li> <!-- End of /.dropdown -->

		        </ul> <!-- End of /.nav-main -->
		    </div>	<!-- /.navbar-collapse -->
		</div>	<!-- /.container-fluid -->
	</nav>	<!-- End of /.nav -->

agents/templates/layout/nav.html
{% load static %}
{% load bootstrap_icons %}
<!-- TOP HEADER Start
    ================================================== -->

	<section id="top">
		<div class="container">
			<div class="row">
				<div class="col-md-7">
					<p class="contact-action"><i class="fa fa-phone-square"></i>Pour plus d'information contacter: <strong>+221 292 90 54</strong></p>
				</div>
				<div class="col-md-2">

				</div>

				<div class="col-md-3 clearfix">
					<ul class="login-cart">
						<li>
							<a data-toggle="modal" data-target="#myModal" href="#">
							{% bs_icon 'person-circle' color='white' size='1.5em' %}
								<span style="font-size:large; position:relative; bottom:30%;">
									connexion
								</span>
							</a>
						</li>
					</ul>
				</div>

			</div> <!-- End Of /.row -->
		</div>	<!-- End Of /.Container -->


	<!-- MODAL Start
    	================================================== -->

		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
		    	<div class="modal-content">
		    		<div class="modal-header">
		        		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		        		<h4 class="modal-title" id="myModalLabel" style="text-align: center;">Portail d'Authentification</h4>
		      		</div>
			      	<div class="modal-body clearfix">
			      		<form action="agents/login"  method="POST" id="login_form" class="std" style="width:100%;">
							{% csrf_token %}
							<fieldset>
								<h3>Se connecter</h3>
								<div class="form_content clearfix">
									<p class="text">
									<label for="email">E-mail address</label>
										<span><input placeholder="Entrer votre adresse" type="text" id="email" name="email" class="account_input" required="required"></span>
									</p>
									<p class="text">
									<label for="passwd">Password</label>
										<span><input placeholder="Entrer votre mot de passe" type="password" id="passwd" name="passwd" class="account_input" required="required"></span>
									</p>
									<p class="lost_password">
										<a href="#popab-password-reset" class="popab-password-link">Avez vous oublié votre mot de passe?</a>
									</p>
									<p class="submit">
										<button type="submit" class="btn btn-success">se connecter</button>
									</p>
								</div>
							</fieldset>
						</form>
			      	</div>
			      	<div class="modal-footer">
			        	<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
			      	</div>
		    	</div>
		  	</div>
		</div>
	</section>  <!-- End of /Section -->



	<!-- LOGO Start
    ================================================== -->

	<header>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<a href="">
						<img src="{% static 'images/logo.png' %}" alt="logo">
					</a>
				</div>	<!-- End of /.col-md-12 -->
			</div>	<!-- End of /.row -->
		</div>	<!-- End of /.container -->
	</header> <!-- End of /Header -->




	<!-- MENU Start
    ================================================== -->

	<nav class="navbar navbar-default">
		<div class="container">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		    </div> <!-- End of /.navbar-header -->

		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      	<ul class="nav navbar-nav nav-main">
		        	<li class="active"><a href="/">ACCUEIL</a></li>
					<li><a href="/">PUBLICATION</a></li>
		        </ul> <!-- End of /.nav-main -->
		    </div>	<!-- /.navbar-collapse -->
		</div>	<!-- /.container-fluid -->
	</nav>	<!-- End of /.nav -->