agents/urls.py
from django.urls import path

from agents.views import index, listagent, saveagent, deleteagent, updateagent, rechercheragent, \
    liste_attribution_agent, list_comptable, index_base, connexionuser, active_compte, rechercher_comptable

app_name = 'mefpai'

urlpatterns = [
    path('', index_base, name='accueil'),
    path('accueil', index_base, name='accueil'),
    path('personnels', listagent, name='list-agent'),
    path('login', connexionuser, name='connexionuser'),
    path('comptables', list_comptable, name='list-comptable'),
    path('rechercher/comptable', rechercher_comptable, name='rechercher_comptable'),
    path('comptables/compte/<int:pk>/', active_compte, name='active_compte'),
    path('comptables/journal/<int:pk>', liste_attribution_agent, name='journal'),
    path('saveAgent', saveagent, name='saveagent'),
    path('personnels/<int:pk>/', updateagent, name='updateAgent'),
    path('personnels/<int:pk>/', deleteagent, name='deleteAgent'),
    path('rechercher', rechercheragent, name='rechercheragent'),
    path('personnels/journal/<int:pk>', liste_attribution_agent, name='journal'),
]

gestionTicket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from agents.views import listagent, saveagent, updateagent, rechercheragent, liste_attribution_agent, list_comptable, \
    connexionuser, index_base

from gestionTicket.views import index

urlpatterns = [
    path('', index, name='index'),
    path('administration/', admin.site.urls),
    path('mefpai/', include('agents.urls'))
]

agents/models.py
from django.db import models

# Create your models here.
from utilisateur.models import Utilisateur


class Agents(models.Model):
    sexe_option = [('m', 'Masculin'), ('f', 'Féminin')]
    direction_option = [('DAGE', 'DAGE'), ('DFPT', 'DFPT'), ('PEJA', 'PEJA'), ('CI', 'Cellule Informatique'), ('CG', 'Cellule Genre')]
    agent_id = models.BigAutoField(primary_key=True)
    first_name = models.CharField(verbose_name='Prénom', blank=False, max_length=100)
    last_name = models.CharField(verbose_name='Nom de famille', blank=False, max_length=100)
    email_institutionnel = models.EmailField(verbose_name='Email Institutionnel', blank=False, unique=True, max_length=100)
    sexe = models.CharField(choices=sexe_option, verbose_name='Sexe', blank=False, max_length=100)
    tel1 = models.CharField(verbose_name='Numéro Téléphone', blank=False, unique=True, max_length=9)
    direction = models.CharField(choices=direction_option, blank=False, verbose_name="Direction", max_length=100)
    post_occupe = models.CharField(verbose_name='Poste Occupé', blank=False, max_length=100)
    autre_tel = models.CharField(verbose_name='Autre Numéro', blank=True, max_length=9)
    utilisateur_ref = models.ForeignKey(Utilisateur, verbose_name='Responsable', blank=False, on_delete=models.CASCADE, related_name='Utilisateur')

agents/forms.py
from django import forms

from agents.models import Agents
from utilisateur.models import Utilisateur


class AgentsForms(forms.ModelForm):
    class Meta:
        sexe_option = [('m', 'Masculin'), ('f', 'Féminin')]
        model = Agents
        fields = ('first_name', 'last_name', 'email_institutionnel','sexe', 'direction', 'tel1', 'post_occupe', 'autre_tel', 'utilisateur_ref')

        widgets = {
            'last_name': forms.TextInput(attrs={'class': 'from-control'}),
            'email_institutionnel': forms.TextInput(attrs={'class': 'from-control'}),
            'sexe': forms.Select(attrs={'class': 'form-control col-sm-2'}),
            'tel1': forms.TextInput(attrs={'class': 'from-control'}),
            'direction': forms.Select(attrs={'class': 'form-control col-sm-2'}),
            'post_occupe': forms.TextInput(attrs={'class': 'from-control'}),
            'autre_tel': forms.TextInput(attrs={'class': 'from-control'}),
            'utilisateur_ref': forms.Select(attrs={'class': 'form-control col-sm-2'})
        }


class UtilisateurForms(forms.ModelForm):
    class Meta:
        sexe_option = [('m', 'Masculin'), ('f', 'Féminin')]
        model = Utilisateur
        fields = ('first_name', 'last_name', 'username', 'password', 'groups','email', 'sexe', 'direction', 'tel1', 'post_occupe', 'is_active')

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'from-control'}),
            'last_name': forms.TextInput(attrs={'class': 'from-control'}),
            'username': forms.TextInput(attrs={'class': 'from-control'}),
            'password': forms.TextInput(attrs={'class': 'from-control', 'type': 'password'}),
            'groups': forms.Select(attrs={'class': 'form-control col-sm-2'}),
            'email': forms.TextInput(attrs={'class': 'from-control'}),
            'sexe': forms.Select(attrs={'class': 'form-control col-sm-2'}),
            'tel1': forms.TextInput(attrs={'class': 'from-control'}),
            'direction': forms.Select(attrs={'class': 'form-control col-sm-2'}),
            'post_occupe': forms.TextInput(attrs={'class': 'from-control'}),
            'autre_tel': forms.TextInput(attrs={'class': 'from-control'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'from-control '}),
        }

agents/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login
# Create your views here.
from agents.forms import AgentsForms, UtilisateurForms
from agents.models import Agents
from django.http import JsonResponse

from attribution.models import Attribution
from utilisateur.models import Utilisateur
from django.contrib.auth import logout


def index(request):
    return render(request, 'accueil.html')


def index_base(request):
    return render(request, 'base.html')


def saveagent(request):
    if request.method == 'POST':
        form = AgentsForms(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('personnels')
    else:
        form = AgentsForms()
        agent = Agents.objects.all()
        return render(request, 'agent.html', {'agent': agent, 'form': form})


def listagent(request):
    form = AgentsForms()
    agent = Agents.objects.all()
    taille = len(agent)
    return render(request, 'agent.html', {'agent': agent, 'form': form, 'taille': taille})


def updateagent(request, pk):
    agent = Agents.objects.get(pk=pk)
    form = AgentsForms(instance=agent)

    if request.method == 'POST':
        form = AgentsForms(request.POST, instance=agent)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('personnels')
    return render(request, 'agent.html', {'agent': agent, 'form': form})


def active_compte(request, pk):
    if pk != '':
        utilisateur = Utilisateur.objects.get(utilisateur_id=pk)
        if utilisateur.is_active:
            utilisateur.is_active = False
            utilisateur.save()
            return HttpResponseRedirect('/mefpai/comptables')
        elif not utilisateur.is_active:
            utilisateur.is_active = True
            utilisateur.save()
            return HttpResponseRedirect('/mefpai/comptables')


def rechercheragent(request):
    form = AgentsForms()
    try:
        if request.method == 'POST':
            email = request.POST['emailagent']
            agent = Agents.objects.get(email_institutionnel=email)
            nbr = 1
            return render(request, 'rechercher.html', {'agent': agent, 'form': form, 'nbr': nbr, 'email': email})
    except:
        agent = ''
        return render(request, 'rechercher.html', {'agent': agent, 'form': form, 'email': email})
    return HttpResponseRedirect('personnels')


def rechercher_comptable(request):
    form = UtilisateurForms()
    try:
        if request.method == 'POST':
            email = request.POST['emailagent']
            agent = Utilisateur.objects.get(email_institutionnel=email)
            nbr = 1
            return render(request, 'recherchercomptable.html', {'agent': agent, 'form': form, 'nbr': nbr, 'email': email})
    except:
        agent = ''
        return render(request, 'recherchercomptable.html', {'agent': agent, 'form': form, 'email': email})
    return HttpResponseRedirect('/mefpai/comptables')


def liste_attribution_agent(request, pk):
    if pk:
        form = AgentsForms()
        agent = Agents.objects.get(pk=pk)
        attribution = Attribution.objects.filter(agent=agent)
        return render(request, 'journal.html', {'agent': agent, 'attribution': attribution, 'form': form})
    return HttpResponseRedirect('personnels')


def list_comptable(request):
    form = UtilisateurForms()
    comptables = Utilisateur.objects.all()
    return render(request, 'comptables.html', {'comptables': comptables, 'form': form})


def deleteagent(request, pk):
    agent = Agents.objects.get(pk=pk)
    agent.objects.delete()
    return render(request, 'delete.html', {'agent': agent})


def connexionuser(request):
    form = AgentsForms()
    try:
        if request.method == 'POST':
            email = request.POST['email']
            passwd = request.POST['passwd']
            user = Utilisateur.objects.get(email_institutionnel=email, password=passwd)
            agent = Agents.objects.all()
            return render(request, 'base.html', {'agent': agent, 'form': form, 'user': user})
        return HttpResponseRedirect('/')
    except:
        return HttpResponseRedirect('/')
    return HttpResponseRedirect('/')


def logout_view(request):
    logout(request)

agents/templates/agent.html
{% extends "layout/baseIndex.html" %}
{% load static %}
{% load bootstrap5 %}
{% load bootstrap_icons %}

{% block content %}
<p>

<section>
		<div class="container">
			<div class="row">
				<br>
				<div class="col-md-4">
					<form action="rechercher" method="POST" class="std" style="width:100%;">
						{% csrf_token %}
						<div class="search-box">
							<div class="input-group">

									<input placeholder="Rechercher par mail" required="required" type="email" name="emailagent" id="emailagent" class="form-control">
									<span class="input-group-btn">
										<button class="btn btn-default" type="submit"></button>
									</span>

							</div><!-- /.input-group -->
						</div><!-- /.search-box -->
					</form>
				</div>

				<div class="col-md-2 clearfix" style="position:relative; left: 38%;">
					<ul class="login-cart">
						<li>
							<a style="border: none; background-color: white;"  href="{% url 'mefpai:list-agent' %}">
									<span style="position:relative; left:10%;">
									{% bs_icon 'arrow-repeat' color='blue' size='1.5em' %}
									</span>
										<br>
									<span style="font-size:medium; color:black;">Actualiser</span>

							</a>
						</li>
					</ul>
				</div>

				<div class="col-md-2 clearfix" style="position:relative; left: 35%;">
					<ul class="login-cart">
						<li>
							<button data-toggle="modal" style="border: none; background-color: white;" data-target="#myAgent" href="#">

									{% bs_icon 'plus-circle' color='blue' size='1.5em' %}
										<br>
									<span style="font-size:medium;">
										Ajouter
									</span>


							</button>
						</li>
					</ul>
				</div>
		</div>	<!-- End Of /.Container -->


	<!-- MODAL Start
    	================================================== -->

		<div class="modal fade" id="myAgent" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
		    	<div class="modal-content">
		    		<div class="modal-header">
		        		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		        		<h4 class="modal-title" id="myModalLabel" style="text-align: center;">Information Agent</h4>
		      		</div>
			      	<div class="modal-body clearfix">
						<div class="form-group">
			      		<form action="saveAgent" method="POST" id="login_form" class="std" style="width:100%;">
							<fieldset>
								<h3 style="tex-align:center;">Formulaire D'identification</h3>
								<div class="form_content clearfix">
										{% csrf_token %}

										{% bootstrap_form form %}

									<div>
										{% buttons %}
											<button type="submit" class="btn btn-primary">
											  Submit
											</button>

											<button class="btn btn-danger" data-dismiss="modal">
												Annuler
											</button>
										{% endbuttons %}
									</div>
								</div>
							</fieldset>
						</form>
						</div>
			      	</div>
			      	<div class="modal-footer">
			        	<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
			      	</div>
		    	</div>
		  	</div>
		</div>

		<div class="modal fade" id="myAgentUpdate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
		    	<div class="modal-content">
		    		<div class="modal-header">
		        		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		        		<h4 class="modal-title" id="myModalLabel" style="text-align: center;">Information Agent</h4>
		      		</div>
			      	<div class="modal-body clearfix">
						<div class="form-group">
			      		<form action="updateagent" method="POST" id="login_form" class="std" style="width:100%;">
							<fieldset>
								<h3 style="tex-align:center;">Formulaire D'identification</h3>
								<div class="form_content clearfix">
										{% csrf_token %}

										{% bootstrap_form form %}

									<div>
										{% buttons %}
											<button type="submit" class="btn btn-primary">
											  Submit
											</button>

											<button class="btn btn-danger" data-dismiss="modal">
												Annuler
											</button>
										{% endbuttons %}
									</div>
								</div>
							</fieldset>
						</form>
						</div>
			      	</div>
			      	<div class="modal-footer">
			        	<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
			      	</div>
		    	</div>
		  	</div>
		</div>
</section>  <!-- End of /Section -->

  {% if agent and taille > 0 %}

	<h1 style="text-align:center; font-weigth: bold;">Liste des Agents De la Direction</h1>
	<div>

		<table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th class="th-sm">Prénom</th>
      <th class="th-sm">Nom</th>
      <th class="th-sm">Email Professionnel</th>
      <th class="th-sm">Sexe</th>
      <th class="th-sm">Téléphone</th>
      <th class="th-sm">Poste Occupé</th>
		<th class="th-sm">Actions</th>

    </tr>
  </thead>
  <tbody>
	{% for a in agent %}
      <tr>
        <td>{{ a.first_name }}</td>
        <td>{{ a.last_name }}</td>
        <td>{{ a.email_institutionnel }}</td>
        <td>
			{% if a.sexe == "m" %}
				<p>Masculin</p>
			{% elif a.sexe == "f" %}
				<p>Féminin</p>
			{% endif %}
		</td>
        <td>{{ a.tel1 }}</td>
        <td>{{ a.post_occupe }}</td>
		  <td>

			  <button style="border: none;" type="button" id="updateButtonModifier" onclick="update_agent_modal('{% url 'mefpai:updateAgent' a.pk %}')">
									{% bs_icon 'pencil-square' color='blue' size='1.5em' %}
			  </button>

			   <a href="{% url 'mefpai:journal' a.pk %}">
				  <button style="border: none;" type="button" id="updateButtonAttribution" >
										{% bs_icon 'journals' color='orange' size='1.5em' %}
				  </button>
			   </a>

			  <button style="border: none;" type="button" id="updateButtonSupprimer" onclick="updateAgentModal('{% url 'mefpai:updateAgent' a.pk %}')">
									{% bs_icon 'trash-fill' color='red' size='1.5em' %}
			  </button>


		  </td>
      </tr>
    {% endfor %}
  </tbody>
  <tfoot>

  </tfoot>
</table>
    </div>

  {% else %}
    <p style="text-align: center; font-weigth: bold;">  Vous n'avez pas d'agent personnel !!! </p>
  {% endif %}



</div>

{% endblock content %}

{% block extrascript %}
	<script  type="text/javascript">
			function update_agent_modal(url){
				alert(url);
				$(#myAgentUpdate).load(url, function(){
					$(this).modal('show');
				});
			}
	</script>
{% endblock extrascript %}

agents/templates/comptables.html
{% extends "layout/baseIndex.html" %}
{% load static %}
{% load bootstrap5 %}
{% load bootstrap_icons %}

{% block content %}
<p>

<section>
		<div class="container">
			<div class="row">
				<br>
				<div class="col-md-4">
					<form action="{% url 'mefpai:rechercher_comptable' %}" method="POST" class="std" style="width:100%;">
						{% csrf_token %}
						<div class="search-box">
							<div class="input-group">

									<input placeholder="Rechercher par mail" required="required" type="email" name="emailagent" id="emailagent" class="form-control">
									<span class="input-group-btn">
										<button class="btn btn-default" type="submit"></button>
									</span>

							</div><!-- /.input-group -->
						</div><!-- /.search-box -->
					</form>
				</div>

				<div class="col-md-2 clearfix" style="position:relative; left: 38%;">
					<ul class="login-cart">
						<li>
							<a style="border: none; background-color: white;"  href="{% url 'mefpai:list-comptable' %}">
									<span style="position:relative; left:10%;">
									{% bs_icon 'arrow-repeat' color='blue' size='1.5em' %}
									</span>
										<br>
									<span style="font-size:medium; color:black;">Actualiser</span>

							</a>
						</li>
					</ul>
				</div>

				<div class="col-md-2 clearfix" style="position:relative; left: 35%;">
					<ul class="login-cart">
						<li>
							<button data-toggle="modal" style="border: none; background-color: white;" data-target="#myAgent" href="#">

									{% bs_icon 'plus-circle' color='blue' size='1.5em' %}
										<br>
									<span style="font-size:medium;">
										Ajouter
									</span>


							</button>
						</li>
					</ul>
				</div>
		</div>	<!-- End Of /.Container -->


	<!-- MODAL Start
    	================================================== -->

		<div class="modal fade" id="myAgent" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
		    	<div class="modal-content">
		    		<div class="modal-header">
		        		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		        		<h4 class="modal-title" id="myModalLabel" style="text-align: center;">Information Comptable</h4>
		      		</div>
			      	<div class="modal-body clearfix">
						<div class="form-group">
			      		<form action="saveAgent" method="POST" id="login_form" class="std" style="width:100%;">
							<fieldset>
								<h3 style="tex-align:center;">Formulaire D'identification</h3>
								<div class="form_content clearfix">
										{% csrf_token %}

										{% bootstrap_form form %}

									<div>
										{% buttons %}
											<button type="submit" class="btn btn-primary">
											  Submit
											</button>

											<button class="btn btn-danger" data-dismiss="modal">
												Annuler
											</button>
										{% endbuttons %}
									</div>
								</div>
							</fieldset>
						</form>
						</div>
			      	</div>
			      	<div class="modal-footer">
			        	<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
			      	</div>
		    	</div>
		  	</div>
		</div>

		<div class="modal fade" id="myAgentUpdate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
		    	<div class="modal-content">
		    		<div class="modal-header">
		        		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		        		<h4 class="modal-title" id="myModalLabel" style="text-align: center;">Information Agent</h4>
		      		</div>
			      	<div class="modal-body clearfix">
						<div class="form-group">
			      		<form action="updateagent" method="POST" id="login_form" class="std" style="width:100%;">
							<fieldset>
								<h3 style="tex-align:center;">Formulaire D'identification</h3>
								<div class="form_content clearfix">
										{% csrf_token %}

										{% bootstrap_form form %}

									<div>
										{% buttons %}
											<button type="submit" class="btn btn-primary">
											  Submit
											</button>

											<button class="btn btn-danger" data-dismiss="modal">
												Annuler
											</button>
										{% endbuttons %}
									</div>
								</div>
							</fieldset>
						</form>
						</div>
			      	</div>
			      	<div class="modal-footer">
			        	<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
			      	</div>
		    	</div>
		  	</div>
		</div>
</section>  <!-- End of /Section -->

	<h1 style="text-align:center; font-weigth: bold;">Liste des Comptables du MEFPAI</h1>
	<div>

		<table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th class="th-sm">Prénom</th>
      <th class="th-sm">Nom</th>
      <th class="th-sm">Email Professionnel</th>
		<th class="th-sm">Role</th>
		<th class="th-sm">Direction</th>
      <th class="th-sm">Téléphone</th>
      <th class="th-sm">Poste Occupé</th>
		<th class="th-sm">Etat Compte && Actions</th>

    </tr>
  </thead>
  <tbody>
	{% for a in comptables %}
      <tr>
        <td>{{ a.first_name }}</td>
        <td>{{ a.last_name }}</td>
        <td>{{ a.email_institutionnel }}</td>
		  <td>
			  {% if a.role == "CP" %}
				<p>Comptable Principale</p>
			{% elif a.role == "CS" %}
				<p>Comptable Secondaire</p>
			{% endif %}
		  </td>
		   <td>{{ a.direction }}</td>
        <td>{{ a.tel1 }}</td>
        <td>{{ a.post_occupe }}</td>
		  <td>
			  {% if a.is_active == 1 %}
			  <a href="{% url 'mefpai:active_compte' a.pk %}">
				   <button style="border: none;" type="button" >
										<span>{% bs_icon 'unlock-fill'  size='1.5em' %}</span>
				  </button>
			  </a>
			{% elif a.is_active == 0 %}
				  <a href="{% url 'mefpai:active_compte' a.pk %}">
					<button style="border: none;" type="button">
										<span>{% bs_icon 'lock-fill'  size='1.5em' %}</span>
					</button>
				  </a>
			{% endif %}
			  <button style="border: none;" type="button" id="updateButtonModifier" onclick="update_agent_modal('{% url 'mefpai:updateAgent' a.pk %}')">
									{% bs_icon 'pencil-square' color='blue' size='1.5em' %}
			  </button>

			   <a href="{% url 'mefpai:journal' a.pk %}">
				  <button style="border: none;" type="button" id="updateButtonAttribution" >
										{% bs_icon 'journals' color='orange' size='1.5em' %}
				  </button>
			   </a>

			  <button style="border: none;" type="button" id="updateButtonSupprimer" onclick="updateAgentModal('{% url 'mefpai:updateAgent' a.pk %}')">
									{% bs_icon 'trash-fill' color='red' size='1.5em' %}
			  </button>


		  </td>
      </tr>
    {% endfor %}
  </tbody>
  <tfoot>

  </tfoot>
</table>
    </div>





</div>

{% endblock content %}

agents/templates/corps.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="UTF-8">
	<title>Food Code Proudly Presents By Themexpert</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

	<!-- Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700' rel='stylesheet' type='text/css'>

	<!-- Css -->
	<link rel="stylesheet" href="{% static 'css/nivo-slider.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/responsive.css' %}">

	<!-- jS -->
	<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/jquery.nivo.slider.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/jquery.nicescroll.js' %}"></script>
	<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}" type="text/javascript"></script>


</head>
<body>

    {% block nav %}
        {% include "layout/nav.html" %}
    {% endblock %}



    {% block footer %}
        {% include "layout/footer.html" %}
    {% endblock %}

	<a id="back-top" href="#"></a>
</body>
</html>